version: 2

project_name: openclaw-docker

before:
  hooks:
    - go test ./...

builds:
  - id: openclaw-docker
    main: .
    binary: openclaw-docker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
      - "-X github.com/schmitthub/openclaw-docker/internal/build.Version={{.Version}}"
      - "-X github.com/schmitthub/openclaw-docker/internal/build.Date={{.Date}}"

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

homebrew_casks:
  - name: openclaw-docker
    ids:
      - default
    binaries:
      - openclaw-docker
    repository:
      owner: schmitthub
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/schmitthub/openclaw-docker
    description: "CLI for building custom OpenClaw Dockerfiles"
    license: "MIT"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openclaw-docker"]
          end

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    args:
      - "sign-blob"
      - "--yes"
      - "${artifact}"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: schmitthub
    name: openclaw-docker
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
