// AUTO-GENERATED by `make update-digests` — do not edit manually.
// Edit image tags in config/defaults.ts, then run `make update-digests`.

export const IMAGE_DIGESTS: Record<string, string> = {
  "debian:bookworm-slim":
    "sha256:74d56e3931e0d5a1dd51f8c8a2466d21de84a271cd3b5a733b803aa91abf4421",
  "envoyproxy/envoy:v1.33-latest":
    "sha256:f91c972d5c99bc133233a079b5663b903e7d56b3b0b0216398924f7b80d09e47",
  "node:22-bookworm":
    "sha256:b501c082306a4f528bc4038cbf2fbb58095d583d0419a259b2114b5ac53d12e9",
  "tailscale/tailscale:v1.94.2":
    "sha256:95e528798bebe75f39b10e74e7051cf51188ee615934f232ba7ad06a3390ffa1",
};
