import {
  BYPASS_SOCKS_PORT,
  DEFAULT_BYPASS_TIMEOUT_SECS,
} from "../config/defaults";

export function renderAgentPrompt(): string {
  return `<environment>
## Environment Constraints
I am running in a Pulumi IaC-managed container stack, not in openclaw gateway's native sandbox mode.

- **Gateway Restarts:** \`openclaw gateway restart\` and all self-restart capabilities **will not work** — a bad config change can crash the gateway unrecoverably. I must ask my user to manually restart; without them I stay stuck. Do not attempt it myself.
- **Config Management:** Pulumi owns infrastructure, server, container configurations. Files under \`.openclaw/\` and the gateway user's home directory are Pulumi-safe and persisted after initial creation; read/modify freely. Use \`config.patch\` for routine changes that don't require a gateway restart (models, tools, subagents) — persists across redeploys and triggers SIGUSR1 live reload.
- **Firewall:** Outbound TCP/UDP heavily restricted; rules managed externally by Pulumi. Always attempt network connections without asking for permission first — if a connection fails due to connectivity issues, report to user: "Connecting to \`<hostname>\` failed due to \`<failure reason>\`. It could be blocked by the firewall. You can either add this to your Pulumi \`egressPolicy\` to give me permanent access (\`{action: allow, dst:<hostname>,proto:<protocol>}\`), or run the escape hatch to give me temporary internet access with \`ssh root@<tailnet.domain>.ts.net \\"firewall-bypass <num seconds>\\"\`." **Permanent** (recurring): ask user to whitelist hostname+port in Pulumi config. **Temporary** (one-off): ask user to open a SOCKS5 proxy on \`localhost:${BYPASS_SOCKS_PORT}\` (auto-closes after ${DEFAULT_BYPASS_TIMEOUT_SECS}s). Cannot open it myself; have the exact command ready **before** asking.

### Using the firewall bypass (once the user opens it)
The bypass opens a SOCKS5 proxy on \`localhost:${BYPASS_SOCKS_PORT}\`. Use any method that works — \`proxychains4\`, explicit proxy flags, or any tool that supports SOCKS5. The proxy handles TCP traffic; DNS is resolved through the proxy when using \`socks5h://\` or \`proxychains4\`.

**proxychains4** (recommended — works with any command transparently):
\`\`\`bash
proxychains4 -f /run/firewall-bypass-proxychains.conf curl https://example.com
proxychains4 -f /run/firewall-bypass-proxychains.conf wget https://example.com/file.tar.gz
proxychains4 -f /run/firewall-bypass-proxychains.conf git clone https://github.com/user/repo.git
proxychains4 -f /run/firewall-bypass-proxychains.conf npm install some-package
proxychains4 -f /run/firewall-bypass-proxychains.conf pip install some-package
\`\`\`

**Explicit proxy flags** (when you only need one command):
\`\`\`bash
curl --proxy socks5h://localhost:${BYPASS_SOCKS_PORT} https://example.com
git -c http.proxy=socks5h://localhost:${BYPASS_SOCKS_PORT} clone https://github.com/user/repo.git
ALL_PROXY=socks5h://localhost:${BYPASS_SOCKS_PORT} wget https://example.com/file.tar.gz
\`\`\`

Note: Use \`socks5h://\` (not \`socks5://\`) to resolve DNS through the proxy. Without the \`h\`, DNS resolves locally and will fail for non-whitelisted domains.

!IMPORTANT: THIS IS IaC AUTOGENERATED. ANY ALTERATION WILL RESULT IN IT BEING REWRITTEN
</environment>
`;
}
