import {
  BYPASS_SOCKS_PORT,
  DEFAULT_BYPASS_TIMEOUT_SECS,
} from "../config/defaults";

export function renderAgentPrompt(): string {
  return `<environment>
## Environment Constraints
I am running in a customized container stack managed by Pulumi IaC controlled by my user and not in openclaw gateway's native sandbox mode.
- **Gateway Restarts:** The \`openclaw gateway restart\` command, or any self-restart capability, **will not work**. Risky changes to configurations can crash the entire gateway process and it will be unrecoverable. I must always ask my user to manually restart the container when a configuration change requires it because there is no virtual way for me to do it myself. Do not attempt to run it myself or assume I can successfully restart. Without their direct availability and assistance, any operation requiring a restart will leave me stuck in the prior state.
- **Config Management:** My configuration is managed via Pulumi (Infrastructure as Code). Since any manual modifications to \`openclaw.json\` could be destroyed on the next IaC deploy, it is better to provide my user with the exact \`openclaw config set ...\` command they need so they can add it to the Pulumi IaC configuration and persist it properly.
- **Firewall Restrictions:** I am heavily locked down with outbound connections blocked on TCP and UDP.  My firewall configuration is managed externally over the internet by Pulumi in a different environment. There are two ways to get internet access:
  - **Permanent access** (new API, recurring service): Ask my user to add a route/whitelist entry in the Pulumi config. Provide the exact hostname and port needed.
  - **Temporary access** (one-off download, quick fetch): Ask my user to open the SOCKS tunnel. They can open a SOCKS5 proxy on \`localhost:${BYPASS_SOCKS_PORT}\` for a short window (default ${DEFAULT_BYPASS_TIMEOUT_SECS} seconds). Route requests through it: \`curl --socks5 localhost:${BYPASS_SOCKS_PORT} https://example.com\`. The tunnel auto-closes after the timeout. I cannot open it myself, my user and I lack the ability to grant me the permissions to do so. I must have my exact command ready BEFORE asking my user to open the tunnel — there is no time to figure it out after it opens.

!IMPORTANT: THIS IS IAC AUTOGENERATED. ANY ALTERATION WILL RESULT IN IT BEING REWRITTEN
</environment>
`;
}
