import {
  CLOUDFLARE_DNS_PRIMARY,
  CLOUDFLARE_DNS_SECONDARY,
} from "../config/defaults";
import type { EgressRule } from "../config/types";
import { mergeEgressPolicy } from "../config/domains";

/**
 * Extract unique domains from merged egress rules for DNS allowlisting.
 * Strips wildcard prefixes (`*.example.com` → `example.com`) since CoreDNS
 * server blocks naturally match all subdomains.
 */
function extractDnsDomains(userRules: EgressRule[]): string[] {
  const merged = mergeEgressPolicy(userRules);
  const domains = new Set<string>();

  for (const rule of merged) {
    if (rule.action === "deny") continue;
    let dst = rule.dst;
    // Strip wildcard prefix — CoreDNS server blocks match subdomains automatically
    if (dst.startsWith("*.")) {
      dst = dst.slice(2);
    }
    // Skip IPs and CIDRs — only domains need DNS resolution
    if (/^[\d./:]+$/.test(dst) || dst.includes(":")) continue;
    domains.add(dst);
  }

  return [...domains].sort();
}

/**
 * Render a CoreDNS Corefile that only resolves whitelisted domains.
 * All other queries return NXDOMAIN. Forwards to Cloudflare malware-blocking DNS.
 */
export function renderCorefile(userRules: EgressRule[] = []): string {
  const domains = extractDnsDomains(userRules);
  const upstreams = `${CLOUDFLARE_DNS_PRIMARY} ${CLOUDFLARE_DNS_SECONDARY}`;

  const domainBlocks = domains
    .map(
      (d) => `${d} {
    errors
    forward . ${upstreams}
}`,
    )
    .join("\n\n");

  return `# Generated by openclaw-deploy. Do not edit directly.
#
# CoreDNS allowlist — only whitelisted domains resolve.
# All other queries return NXDOMAIN.
# Forwards to Cloudflare malware-blocking DNS (${upstreams}).
#
# This file mirrors the domain whitelist in envoy.yaml.
# DNS queries from uid 1000 (node) are redirected here by iptables in sidecar-entrypoint.sh.

${domainBlocks}

# Catch-all: NXDOMAIN for everything else
. {
    template ANY ANY {
        rcode NXDOMAIN
    }
    log
}
`;
}
