/**
 * Renders the gateway container entrypoint script.
 *
 * The gateway shares the sidecar's network namespace (network_mode: container:).
 * All networking (iptables, routing, tailscaled) is handled by the sidecar.
 * This entrypoint only needs to:
 * 1. Fix permissions
 * 2. Start sshd for Tailscale Serve TCP forwarding
 * 3. Drop to node user via gosu
 */
export function renderEntrypoint(): string {
  return `#!/bin/bash
# Generated by openclaw-deploy. Runs as root, drops to node via gosu.
#
# The sidecar container handles all networking (iptables, routing, tailscaled).
# This entrypoint starts sshd and drops privileges.
set -euo pipefail

# Tighten config dir permissions (bind mounts inherit host perms, this fixes both sides).
chown node:node /home/node/.openclaw 2>/dev/null || true
chmod 700 /home/node/.openclaw 2>/dev/null || true

# Fix git safe.directory for linuxbrew repo (volume UID mismatch).
# Homebrew repos are owned by the linuxbrew user but node runs brew.
# Git refuses to operate on repos owned by a different user without this exception.
if command -v git >/dev/null 2>&1; then
  gosu node git config --global --get-all safe.directory 2>/dev/null \\
    | grep -qF "/home/linuxbrew/.linuxbrew/Homebrew" \\
    || gosu node git config --global --add safe.directory /home/linuxbrew/.linuxbrew/Homebrew
fi

# Start sshd for Tailscale Serve TCP forwarding (SSH access via Tailscale).
/usr/sbin/sshd

# Drop privileges and exec the CMD as the node user.
exec gosu node "$@"
`;
}
