import {
  COREDNS_CONTAINER_PATH,
  COREDNS_PORT,
  FILEBROWSER_PORT,
} from "../config/defaults";

/**
 * Renders the gateway container entrypoint script.
 *
 * The gateway shares the sidecar's network namespace (network_mode: container:).
 * All networking (iptables, routing, tailscaled) is handled by the sidecar.
 * This entrypoint only needs to:
 * 1. Fix permissions
 * 2. Start sshd for Tailscale Serve TCP forwarding
 * 3. Start CoreDNS allowlist proxy (mandatory, with crash monitor)
 * 4. Start filebrowser (optional)
 * 5. Drop to node user via gosu
 */
export function renderEntrypoint(): string {
  return `#!/bin/bash
# Generated by openclaw-deploy. Runs as root, drops to node via gosu.
#
# The sidecar container handles all networking (iptables, routing, tailscaled).
# This entrypoint starts sshd, CoreDNS, filebrowser, and drops privileges.
set -euo pipefail

# Tighten config dir permissions (bind mounts inherit host perms, this fixes both sides).
chown node:node /home/node/.openclaw 2>/dev/null || true
chmod 700 /home/node/.openclaw 2>/dev/null || true

# Fix git safe.directory for linuxbrew repo (volume UID mismatch).
# Homebrew repos are owned by the linuxbrew user but node runs brew.
# Git refuses to operate on repos owned by a different user without this exception.
if command -v git >/dev/null 2>&1; then
  gosu node git config --global --get-all safe.directory 2>/dev/null \\
    | grep -qF "/home/linuxbrew/.linuxbrew/Homebrew" \\
    || gosu node git config --global --add safe.directory /home/linuxbrew/.linuxbrew/Homebrew
fi

# Start sshd for Tailscale Serve TCP forwarding (SSH access via Tailscale).
/usr/sbin/sshd || { echo "ERROR: sshd failed to start" >&2; exit 1; }
sleep 0.5
if ! pgrep -x sshd >/dev/null 2>&1; then
  echo "ERROR: sshd exited immediately after start — check /etc/ssh/sshd_config" >&2
  exit 1
fi

# Start CoreDNS allowlist proxy (runs as root so upstream queries bypass UDP DROP).
# Listens on port ${COREDNS_PORT}; sidecar iptables redirects uid 1000 DNS here.
# CoreDNS is mandatory — the sidecar unconditionally redirects DNS to this port.
if [ ! -x /usr/local/bin/coredns ]; then
  echo "ERROR: coredns binary not found at /usr/local/bin/coredns" >&2
  exit 1
fi
if [ ! -f ${COREDNS_CONTAINER_PATH} ]; then
  echo "ERROR: CoreDNS Corefile not found at ${COREDNS_CONTAINER_PATH}" >&2
  exit 1
fi
/usr/local/bin/coredns -conf ${COREDNS_CONTAINER_PATH} -dns.port ${COREDNS_PORT} &
sleep 0.5
if ! pgrep -x coredns >/dev/null 2>&1; then
  echo "ERROR: CoreDNS exited immediately after start — DNS allowlist is NOT active" >&2
  exit 1
fi

# Monitor CoreDNS — if it dies after startup, exit to trigger container restart.
# CoreDNS runs as a background process (not PID 1), so Docker won't detect its death.
# Must disable set -e: pgrep returns exit 1 when no match, which would kill the subshell.
(
  set +e
  trap 'echo "WARN: CoreDNS monitor exited unexpectedly" >&2' EXIT
  while true; do
    if ! pgrep -x coredns >/dev/null 2>&1; then
      echo "FATAL: CoreDNS died — exiting to trigger container restart" >&2
      kill 1
      break
    fi
    sleep 10
  done
) &

# Start filebrowser on loopback (accessible only via Tailscale Serve at /browse).
if command -v filebrowser >/dev/null 2>&1; then
  gosu node filebrowser --address 127.0.0.1 --port ${FILEBROWSER_PORT} --noauth --root /home/node --baseurl /browse &
fi

# Drop privileges and exec the CMD as the node user.
exec gosu node "$@"
`;
}
