import { EgressRule } from "../config/types";
import { mergeEgressPolicy } from "../config/domains";
import {
  ENVOY_EGRESS_PORT,
  ENVOY_DNS_PORT,
  CLOUDFLARE_DNS_PRIMARY,
  CLOUDFLARE_DNS_SECONDARY,
} from "../config/defaults";

export interface EnvoyConfigResult {
  yaml: string;
  warnings: string[];
}

/**
 * Renders envoy.yaml from an egress policy.
 *
 * Egress-only: no ingress listener, no openclaw_gateway cluster, no TLS certs.
 * Tailscale handles all ingress. Envoy handles transparent egress + DNS.
 */
export function renderEnvoyConfig(
  userRules: EgressRule[] = [],
): EnvoyConfigResult {
  const warnings: string[] = [];
  const merged = mergeEgressPolicy(userRules);

  // Collect TLS passthrough domains and emit warnings for unsupported rule types
  const passthroughDomains: string[] = [];

  for (const rule of merged) {
    if (rule.action === "deny") {
      // Deny rules don't add to filter chains — default deny handles them
      continue;
    }

    switch (rule.proto) {
      case "tls":
        if (rule.inspect) {
          warnings.push(
            `MITM TLS inspection not yet implemented for "${rule.dst}" — treating as passthrough (Phase 2)`,
          );
        }
        passthroughDomains.push(rule.dst);
        break;

      case "ssh":
        warnings.push(
          `SSH egress rule for "${rule.dst}" skipped — requires DNS snooping (Phase 2)`,
        );
        break;

      case "tcp":
        warnings.push(
          `TCP egress rule for "${rule.dst}" skipped — requires DNS snooping (Phase 2)`,
        );
        break;
    }
  }

  const domainLines = passthroughDomains
    .map((d) => `        - "${d}"`)
    .join("\n");

  const yaml = `# Generated by openclaw-deploy. Do not edit directly.
#
# Envoy egress-only proxy: transparent TLS proxy + DNS forwarder.
# Ingress is handled by Tailscale (no ingress listener here).
# Egress uses TLS Inspector + SNI-based domain whitelist. No MITM / TLS termination.
# All outbound TCP from the gateway is DNAT'd here by iptables in entrypoint.sh.
# Restart after editing: docker compose restart envoy

static_resources:
  listeners:
  # Egress: transparent TLS proxy with SNI-based domain whitelist.
  # All outbound TCP from the gateway is DNAT'd here by iptables.
  # TLS Inspector reads SNI from ClientHello (no TLS termination / MITM).
  # Whitelisted SNI -> forwarded. Everything else -> connection refused.
  - name: egress
    address:
      socket_address:
        address: 0.0.0.0
        port_value: ${ENVOY_EGRESS_PORT}
    listener_filters:
    - name: envoy.filters.listener.tls_inspector
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:
    # Whitelisted TLS domains (matched by SNI from ClientHello).
    - filter_chain_match:
        server_names:
${domainLines}
      filters:
      - name: envoy.filters.network.sni_dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3.FilterConfig
          port_value: 443
          dns_cache_config:
            name: dynamic_forward_proxy_cache
            dns_lookup_family: V4_PREFERRED
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: egress_tls_allowed
          cluster: dynamic_forward_proxy_cluster
    # Default deny: non-whitelisted SNI or non-TLS traffic.
    # Connection is immediately reset (deny_cluster has no endpoints).
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: egress_denied
          cluster: deny_cluster

  # DNS: forward resolver for containers on the internal network.
  # Docker's embedded DNS cannot forward external queries from internal-only
  # networks. Gateway services use dns: [172.28.0.2] (Envoy's static IP)
  # so Docker DNS forwards here instead of failing with SERVFAIL.
  # Upstream: Cloudflare ${CLOUDFLARE_DNS_PRIMARY} / ${CLOUDFLARE_DNS_SECONDARY} (malware-blocking DNS).
  - name: dns
    address:
      socket_address:
        address: 0.0.0.0
        port_value: ${ENVOY_DNS_PORT}
        protocol: UDP
    listener_filters:
    - name: envoy.filters.udp.dns_filter
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.udp.dns_filter.v3.DnsFilterConfig
        stat_prefix: dns
        client_config:
          resolver_timeout: 5s
          max_pending_lookups: 256
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
              - socket_address:
                  address: "${CLOUDFLARE_DNS_PRIMARY}"
                  port_value: 53
              - socket_address:
                  address: "${CLOUDFLARE_DNS_SECONDARY}"
                  port_value: 53

  clusters:
  - name: dynamic_forward_proxy_cluster
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache
          dns_lookup_family: V4_PREFERRED

  - name: deny_cluster
    type: STATIC
    connect_timeout: 0.25s
    load_assignment:
      cluster_name: deny_cluster
`;

  return { yaml, warnings };
}
