#!/usr/bin/env bash
set -euo pipefail

# Reads image tags from config/defaults.ts, fetches current multi-arch manifest
# digests, and writes them to config/digests.ts (a separate generated file).
#
# To change a base image (e.g. node:22→24), edit the tag in defaults.ts and re-run.
#
# Usage: ./scripts/update-base-digests.sh
# Requires: docker (with buildx plugin), jq

DEFAULTS_FILE="config/defaults.ts"
DIGESTS_FILE="config/digests.ts"

if [ ! -f "$DEFAULTS_FILE" ]; then
  echo "ERROR: $DEFAULTS_FILE not found. Run from repo root." >&2
  exit 1
fi

command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required but not installed" >&2; exit 1; }
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker is required but not installed" >&2; exit 1; }

# Extract image tags from _TAG variables in defaults.ts
mapfile -t IMAGES < <(
  grep -oE '_TAG\s*=\s*"[^"]+"' "$DEFAULTS_FILE" \
    | grep -oE '"[^"]+"' \
    | sed 's/"//g' \
    | sort -u
)

if [ ${#IMAGES[@]} -eq 0 ]; then
  echo "ERROR: no _TAG image variables found in $DEFAULTS_FILE" >&2
  exit 1
fi

echo "Found ${#IMAGES[@]} image tag(s) in $DEFAULTS_FILE:"

# Build the digests file
{
  echo "// AUTO-GENERATED by \`make update-digests\` — do not edit manually."
  echo "// Edit image tags in config/defaults.ts, then run \`make update-digests\`."
  echo ""
  echo "export const IMAGE_DIGESTS: Record<string, string> = {"
} > "$DIGESTS_FILE"

for image in "${IMAGES[@]}"; do
  printf "  %-40s " "$image"

  if ! output=$(docker buildx imagetools inspect "$image" --format '{{json .Manifest}}' 2>&1); then
    echo "ERROR: docker buildx imagetools inspect failed for $image:" >&2
    echo "$output" >&2
    exit 1
  fi

  if ! digest=$(echo "$output" | jq -r '.digest // empty'); then
    echo "ERROR: jq failed to parse manifest for $image" >&2
    exit 1
  fi

  if [ -z "$digest" ]; then
    echo "ERROR: manifest for $image has no digest field. Raw output:" >&2
    echo "$output" >&2
    exit 1
  fi

  if [[ ! "$digest" =~ ^sha256:[a-f0-9]{64}$ ]]; then
    echo "ERROR: unexpected digest format for $image: $digest" >&2
    exit 1
  fi

  echo "-> ${digest:0:19}..."

  # Append to digests file
  echo "  \"${image}\":" >> "$DIGESTS_FILE"
  echo "    \"${digest}\"," >> "$DIGESTS_FILE"
done

echo "};" >> "$DIGESTS_FILE"

echo "Wrote $DIGESTS_FILE. Review: git diff $DIGESTS_FILE"
